### ISSUE TITLE
memset not instrumented

### ISSUE THREAD

**Issue by Teemperor** [bajinsheng/ReZZan#2]
I'm trying to reproduce the ReZZan results and I noticed that `memset` is not instrumented by the rezzan_runtime. Given it's a major part of the workload of most of the fuzzed binaries, I want to fix it before doing a fuzzing evaluation. I attached my local diff below to confirm this would be the intended way for ReZZan to implement the poison check?

```diff
diff --git a/rezzan_runtime.c b/rezzan_runtime.c
index 3e77d07..d6c9131 100644
--- a/rezzan_runtime.c
+++ b/rezzan_runtime.c
@@ -824,6 +824,23 @@ void *memcpy(void * restrict dst, const void * restrict src, size_t n)
     return dst;
 }
 
+/*
+ * The glib runtime support.
+ */
+void *__ni_memset(void *dst, int c, size_t n)
+{
+    uint8_t *dst8 = (uint8_t *)dst;
+    for (size_t i = 0; i < n; i++)
+        dst8[i] = c;
+    return dst;
+}
+
+void *memset(void *dst, int c, size_t n)
+{
+    check_poisoned(dst, n);
+    return __ni_memset(dst, c, n);
+}
+
 void *memmove(void * restrict dst, const void * restrict src, size_t n)
 {
     check_poisoned(dst, n);
```

**Comment by bajinsheng** [comment]
We did not test it, so it is better to use it with caution as `memset` is called in other glibc functions.

**Comment by bajinsheng** [comment]
And also all bugs in our benchmark can be found without this instrument
